### ISSUE TITLE
Add ability to change password

### ISSUE THREAD

**Issue by brylie** [GeriLife/companionship-care#54]
Currently, there is no way for users to change their password.

## Task

- [x] add a password change page
- [x] add a link in the navigation menu to a "change password" page

**Comment by Marsh-sudo** [comment]
Hello, Created a branch for this issue. Solved it and it works well. Waiting for you to accept my PR :)

**Comment by brylie** [comment]
Very cool! I've assigned you to this task and reviewed the pull request with minor change suggestions :-)

**Comment by brylie** [comment]
Closed by #79 

Thanks, @Marsh-sudo! I made sure to credit you in the commit and our project contributors section :-)
